### ISSUE TITLE
"Legacy autograd function with non-static forward method is deprecated. "

### ISSUE THREAD

**Issue by Godricwang** [locuslab/mpc.pytorch#28]
When running the example "Time Varying Linear-Quadratic Control" with Pytorch 1.5.1, the following error appears, 
=================
 "Legacy autograd function with non-static forward method is deprecated. "

RuntimeError: Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)
=================

Running the example in the Jupyter Notebook generates the same error.

**Comment by drewjgray** [comment]
I am getting the same issue, which also looks to be the reason the CI build is failing. Is there any plan to update the code base?

**Comment by bhargavajs07** [comment]
@Godricwang , @drewjgray  Did you manage to find a fix for this issue ?

**Comment by Juju-botu** [comment]
Hi, I made some tweaks to the code and created a pull request; seems to be working fine now. I'll include here the changelog in the meantime:

- Change `LQRStep` from `autograd.Functional` to `nn.Module` for compatibility (more info about legacy autograd function with non-static method [here](https://discuss.pytorch.org/t/legacy-autograd-function-with-non-static-forward-method-is-deprecated-and-will-be-removed-in-1-3/69869) and [here](https://github.com/NVIDIA/flownet2-pytorch/pull/207/commits/40b5bf9a220f58c3d0317204cf339028762b5789))
- Commented out `save_for_backward` (not needed in `nn.Module` apparently since it is using the Functional API for saving the weights by default, more info [here](https://discuss.pytorch.org/t/what-is-the-difference-between-torch-nn-and-torch-nn-functional/33597/7))
- `LQRStep` returns backward and forward trajectory by default
- Add local import in test files
- Add Circle CI testing (you can change the account info later)
- Miscellaneous fixes

**Comment by bamos** [comment]
Updated in https://github.com/locuslab/mpc.pytorch/commit/bf19cd4405d8242e93f4c0a5464739f98798a833
