### ISSUE TITLE
FunctionBackward.forward error

### ISSUE THREAD

**Issue by kaushikb258** [locuslab/mpc.pytorch#38]
I get the following error. Probably a pytorch version issue. Any suggestions?

TypeError: FunctionBackward.forward: expected Tensor or tuple of Tensor (got lqrBackOut) for return value 2

**Comment by bamos** [comment]
It's because the `back_out` type here is a `NamedTuple` and not a `Tensor`: https://github.com/locuslab/mpc.pytorch/blob/master/mpc/lqr_step.py#L307

This could be patched by removing `back_out` and `for_out` from the return and also updating everywhere else this is used, and potentially saving them to the class or returning the information there in another way if you need it.

**Comment by bamos** [comment]
Updated in https://github.com/locuslab/mpc.pytorch/commit/bf19cd4405d8242e93f4c0a5464739f98798a833
